[tool.poetry]
name = "xer-reader"
version = "0.1.0"
description = ""
authors = ["Jesse Jones <code@seqmanagement.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
